### ISSUE TITLE
Project treeview weirdness

### ISSUE THREAD

**Issue by blitz-research** [engor/Ted2Go#12]
Hi,

Sometimes when you click on a folder in the project treeview, nothing happens.

Weirder: sometimes when you click on an open folder in the project treeview, the folder remains open but all the '>' icons for all child folders disappear, making it look a bit like the contents of all child folders have been deleted (they haven't)!

Can't get it to happen with plain Ted2.

Bye!
Mark

**Comment by engor** [comment]
This problem relay on my attempt to set custom icon to root projects nodes - instead of default 'folder' icon. I don't know why this happen, but you can help me with a small mojox 'fix'. :)

All I need from **mojox.FileBrowser** this time is ability to override its icons. A simple way to do that is to add GetFileTypeIcon virtual method that users can override for their needs.

If you'll just add this into mojox.FileBrowser:
```
Protected
Method GetFileTypeIcon:Image( path:String ) Virtual
	
	Local icon:=_fileTypeIcons[ExtractExt( path ).ToLower()]
	Return icon
End
```
and replace 'raw' 
`Local icon:=_fileTypeIcons[ExtractExt( f ).ToLower()]` 
with 
`Local icon:=GetFileTypeIcon( f )`

then I'll can simplify my code and that probably fix discussed issue.

**Comment by blitz-research** [comment]
> Method GetFileTypeIcon:Image( path:String ) Virtual

Added to develop branch.

On Thu, Jan 12, 2017 at 4:44 PM, Evgeniy Goroshkin <notifications@github.com

**Comment by engor** [comment]
Mark, there is a mistake in code:

```
Method GetFileTypeIcon:Image( path:String ) Virtual

	Local ext:=ExtractExt( path )
	If Not ext Return Null
	
	Return **GetFileTypeIcons**()[ ext.ToLower() ] '<-- HERE
End
```
inside of method we should use our map **_fileTypeIcons** of course.

**Comment by blitz-research** [comment]
Cheeky banana!


On Mon, Jan 16, 2017 at 3:54 PM, Evgeniy Goroshkin <notifications@github.com

**Comment by engor** [comment]
Fixed but not via using GetFileTypeIcon (I need this method anyway).
If we remove treeview child - we lost 'folder' icons.
To fix I just call Update (icons) after removing nodes (was before).
