### ISSUE TITLE
Can't rename file when only chance is upper case to lower case

### ISSUE THREAD

**Issue by Difference** [engor/Ted2Go#141]
In Project pane, trying to rename "Myfile.monkey2" to "my file.monkey2" results in "File Already exists"

**Comment by engor** [comment]
What your desktop OS?

**Comment by Difference** [comment]
Sorry, Mac OS High Sierra

**Comment by engor** [comment]
There is the check
```
If GetFileType( newPath )=FileType.File
	Alert( "File already exists! Path: '"+newPath+"'" )
	Return
Endif
```
Function `GetFileType` is located at `std.filesystem` and use c++ function `stat`.
Looks like mx2-related bug.

**Comment by blitz-research** [comment]
This is because of case-insensitive filesystem.

To fix, we need a way to get 'real' filename and compare that instead (you could scan parent dir using LoadDir for matching filename I guess) - even then, I think libc.rename would probably fail but again you could get around this by using tmp intemmediate name (as long as that didn't also exist!).

It used to be a problem on windows desktop too, eg: you couldn't rename 'text.txt' to 'Test.txt' but it looks like they've hacked around that in Windows 10 at least.

**Comment by engor** [comment]
Solution with move-to-tmp should work.
Will make it for files.

**Comment by engor** [comment]
Pushed into `dev`.
