### ISSUE TITLE
Please add an option to disable auto-indentation on new lines.

### ISSUE THREAD

**Issue by ImmutableOctet** [engor/Ted2Go#28]
The original Ted2 does not add a tab/spaces after pressing enter when declaring a function, but Ted2Go does. Please add an option to toggle this behavior. I'd prefer to stay at the same indentation level when declaring a function body.

I don't write the contents of a function before specifying its declaration and end-point, so auto-indenting like this means I have to hit backspace every time I write a function.

**Comment by nitrologic** [comment]
I am same, Indent After Declaration = Off would be most welcome.

**Comment by engor** [comment]
I want to add feature "auto-closing declaration" by ctrl+enter (jentos.code has such).
With that feature - when you declaring new stuff like function/method/for/class/etc you just press `ctrl+enter` instead of single enter and you'll get 'End' automatically. :)

`Function Test() [ctrl+enter]`
-->
```
Function Test()
    | (cursor with indentation)
End
```
Option to disable indentation also good idea, will add.

**Comment by engor** [comment]
Added option "Auto indentation" to Preferences. :)
